### ISSUE TITLE
Data sciences

### ISSUE THREAD

**Issue by hoco1** [DistroTEAM/wish#2]
Hey folks
I have three idea, and I want to do it and if your team like to contribute to me, I'm so Appreciate you
First I want to create news classification, for example when I send text of some category of news to program show me the category of news it's really better support my native language (Farsi)
آرژانتین یک - برزیل صفر/ پایان حسرت ۲۸ ساله آلبی‌سلسته؛ اولین جام ملی در دستان مسی → category : sport  😄 
second, I wanna trustworthy model for predict stocks price 
for example, say next day price for period one month of tesla
third, I want to create a dashboard for COVID-19
tnx for this community

**Comment by BlackIQ** [comment]
Hey.

I'll help you in Covid idea.
Create the repository in your account then you and me will work on it as soon as possible.

Live long and prosper.
Amir.

**Comment by PrabodhBadwaik27** [comment]
Hey @hoco1 and @BlackIQ 
please consider me in to assist in Covid-19 dashboard.

**Comment by hoco1** [comment]
Hey bro, sounds great 
which one of these do you prefer to work 'power bi', 'tableau','qlikview'

**Comment by PrabodhBadwaik27** [comment]
I will like to go with PowerBI. Suggest me if you feel that Tableau or Qlikview will have any upper-hand

**Comment by shabane** [comment]
@hoco1 
@BlackIQ 
@Aazerra 
dont you started yet ?

**Comment by BlackIQ** [comment]
I have less knowledge therefore cant help dear friends.
